serenity {
  project.name = "AUTO_FRONT_SCREENPLAY"
  take.screenshots = AFTER_EACH_STEP
  restart.browser.for.each = scenario
}

webdriver {
  driver = chrome
  base.url = "http://localhost:5173"
  timeouts {
    implicitlywait = 5000
    fluentwait = 10000
  }
}

chrome {
  switch = "--start-maximized;--disable-notifications;--remote-allow-origins=*"
}

headless.mode = false

